spring:
  application:
    name: binarfood-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_APP_ID}
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka