version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=binarfud_naomi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre

volumes:
  postgres-db: